---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/deployment

inputs:
  - name: jumpbox-deployment

run:
  path: jumpbox-deployment/ci/tasks/unit-test.sh
