---
resources:
- name: jumpbox-deployment
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/jumpbox-deployment.git
    private_key: ((jumpbox_deployment_readwrite_deploy_key.private_key))
    ignore_paths:
    - README.md

- name: stemcell-aws
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent

- name: cpi-aws
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-aws-cpi-release

- name: stemcell-azure
  type: bosh-io-stemcell
  source:
    name: bosh-azure-hyperv-ubuntu-bionic-go_agent

- name: cpi-azure
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-azure-cpi-release

- name: stemcell-gcp
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-bionic-go_agent

- name: cpi-gcp
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-google-cpi-release

- name: stemcell-openstack
  type: bosh-io-stemcell
  source:
    name: bosh-openstack-kvm-ubuntu-bionic-go_agent

- name: cpi-openstack
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-openstack-cpi-release

- name: stemcell-vsphere
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-bionic-go_agent

- name: cpi-vsphere
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-vsphere-cpi-release

jobs:
- name: unit-test
  serial: true
  public: false
  plan:
  - get: jumpbox-deployment
    trigger: true
  - task: unit-test
    file: jumpbox-deployment/ci/tasks/unit-test.yml

- name: bump-stemcells
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: jumpbox-deployment
    - get: stemcell-aws
      trigger: true
      params:
        tarball: false
    - get: stemcell-azure
      params:
        tarball: false
      trigger: true
    - get: stemcell-gcp
      params:
        tarball: false
      trigger: true
    - get: stemcell-openstack
      params:
        tarball: false
      trigger: true
    - get: stemcell-vsphere
      params:
        tarball: false
      trigger: true

  - task: same-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cloudfoundry/cf-deployment-concourse-tasks
      inputs:
      - name: stemcell-aws
      - name: stemcell-azure
      - name: stemcell-gcp
      - name: stemcell-vsphere
      - name: stemcell-openstack
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash

          set -eu

          count="$(for v in $(ls stemcell-*/version); do cat $v; echo ""; done | sort -u | wc -l)"
          if [[ "$count" != "1" ]]; then
            echo "Stemcells version mismatch detected."
            exit 1
          fi

  - task: bump-stemcell
    file: jumpbox-deployment/ci/tasks/bump-stemcell.yml

  - task: unit-test
    file: jumpbox-deployment/ci/tasks/unit-test.yml
    input_mapping:
      jumpbox-deployment: updated-jumpbox-deployment

  - put: jumpbox-deployment
    params:
      repository: updated-jumpbox-deployment
      rebase: true

- name: bump-cpis
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: jumpbox-deployment
    - get: cpi-aws
      params:
        tarball: false
      trigger: true
    - get: cpi-azure
      params:
        tarball: false
      trigger: true
    - get: cpi-gcp
      params:
        tarball: false
      trigger: true
    - get: cpi-openstack
      params:
        tarball: false
      trigger: true
    - get: cpi-vsphere
      params:
        tarball: false
      trigger: true

  - task: bump-cpis
    file: jumpbox-deployment/ci/tasks/bump-cpi.yml

  - task: unit-test
    file: jumpbox-deployment/ci/tasks/unit-test.yml
    input_mapping:
      jumpbox-deployment: updated-jumpbox-deployment

  - put: jumpbox-deployment
    params:
      repository: updated-jumpbox-deployment
      rebase: true
